OC\TicketingBundle\Entity\Commande:
    type: entity
    table: null
    repositoryClass: OC\TicketingBundle\Repository\CommandeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        ticketId:
            type: integer
            column: Ticket_id
        price:
            type: integer
            column: Price
    lifecycleCallbacks: {  }
