OC\TicketingBundle\Entity\Ticket:
    type: entity
    table: null
    repositoryClass: OC\TicketingBundle\Repository\TicketRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255
            column: Type
        date:
            type: date
            column: Date
        owner:
            type: string
            length: 255
            column: Owner
    lifecycleCallbacks: {  }
