
oc_ticketing_home:
    path:     /
    defaults: { _controller: OCTicketingBundle:Index:index }
    
oc_ticketing_check:
    path:     /check
    defaults: { _controller: OCTicketingBundle:Index:check }
    
oc_ticketing_payment:
    path:     /payment
    defaults: { _controller: OCTicketingBundle:Index:payment }

oc_ticketing_valid:
    path:     /valid
    defaults: { _controller: OCTicketingBundle:Index:valid }

oc_ticketing_error:
    path:     /error
    defaults: { _controller: OCTicketingBundle:Index:error }
    