services:
    oc_ticketing.pricecalculator:
        class: OC\TicketingBundle\PriceCalculator\OCPriceCalculator
    oc_ticketing.mailer:
        class: OC\TicketingBundle\Mailer\OCMailer
        arguments: ['@templating', '@mailer']